set(CMAKE_SYSTEM_NAME QNX)
set(CMAKE_SYSTEM_VERSION 8.0)

if(NOT DEFINED ENV{QNX_HOST} OR NOT DEFINED ENV{QNX_TARGET})
    message(FATAL_ERROR "Please source the QNX SDP environment before configuring the project.")
endif()

set(QNX_HOST $ENV{QNX_HOST})
set(QNX_TARGET $ENV{QNX_TARGET})

set(CMAKE_C_COMPILER qcc)
set(CMAKE_CXX_COMPILER q++)

set(CMAKE_C_FLAGS_INIT "-Vgcc_ntoaarch64le")
set(CMAKE_CXX_FLAGS_INIT "-Vgcc_ntoaarch64le_gpp")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Vgcc_ntoaarch64le_gpp")

set(CMAKE_FIND_ROOT_PATH ${QNX_TARGET})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
